// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeFLkUsWDUmNaD955ZdIQtWXWK0p9iDic',
    appId: '1:897557563509:web:e493c499b924d36e65103c',
    messagingSenderId: '897557563509',
    projectId: 'to-do-4317b',
    authDomain: 'to-do-4317b.firebaseapp.com',
    storageBucket: 'to-do-4317b.appspot.com',
    measurementId: 'G-JJ48CJJTGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs92yeRYsD62MM7BUJlQyUn8vJCEw6-w8',
    appId: '1:897557563509:android:11b02ff852ed4b9065103c',
    messagingSenderId: '897557563509',
    projectId: 'to-do-4317b',
    storageBucket: 'to-do-4317b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOtdJsXRST6nR1h97MF0KUFHlCL4L0U4U',
    appId: '1:897557563509:ios:5e7477753c74f36d65103c',
    messagingSenderId: '897557563509',
    projectId: 'to-do-4317b',
    storageBucket: 'to-do-4317b.appspot.com',
    iosClientId:
        '897557563509-ilcsg8mtetooi87l46827kr4blsesfbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );
}
